{
 "title": "Highlights: Linux OS",
 "tags": [
  "OS",
  "Linux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_system\") + mean(\"usage_user\") as mean FROM \"cpu\" WHERE $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "target": "aliasByTags(keepLastValue(seriesByTag('name=opvagent.cpu.usage_idle', 'cpu=cpu-total'), 60), 'host')"
    }
   ]
  },
  {
   "title": "Memory in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Current" ], "type": "alias" }
      ]
     ],
     "target": "aliasByTags(keepLastValue(seriesByTag('name=opvagent.mem.used_percent'), 60), 'host')"
    }
   ]
  },
  {
   "title": "Swap Used %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "target": "aliasByTags(keepLastValue(seriesByTag('name=opvagent.swap.used_percent'), 60), 'host')"
    }
   ]
  },
  {
   "title": "Reads per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_host $tag_name",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByTags(seriesByTag('name=opvagent.diskio.reads'), 'host', '_name')"
    }
   ]
  },
  {
   "title": "Writes per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_host $tag_name",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByTags(seriesByTag('name=opvagent.diskio.writes'), 'host', '_name')"
    }
   ]
  },
  {
   "title": "Read Throughput per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host $tag_name",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByTags(seriesByTag('name=opvagent.diskio.read_bytes'), 'host', '_name')"
    }
   ]
  },
  {
   "title": "Write Throughput per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host $tag_name",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByTags(seriesByTag('name=opvagent.diskio.write_bytes'), 'host', '_name')"
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "target": "aliasByTags(keepLastValue(seriesByTag('name=opvagent.disk.used_percent'), 60), 'host', 'device')"
    }
   ]
  },
  {
   "title": "Free Space Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "target": "aliasByTags(scale(keepLastValue(seriesByTag('name=opvagent.disk.free'), 60), 1e-9), 'host', 'device')"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "target": "aliasByTags(keepLastValue(seriesByTag('name=opvagent.processes.total'), 60), 'host')"
    }
   ]
  }
 ]
}